const CHARACTERS = {
  poodle: {
    id: 'poodle',
    name: '푸들',
    emoji: '🐩',
    body: 0xf5deb3,
    bodyHighlight: 0xfaebd7,
    ear: 0xe8d5b7,
    eyeColor: 0x222222,
    noseColor: 0x444444,
    earType: 'round',
    features: ['curlyFur'],
  },
  shiba: {
    id: 'shiba',
    name: '시바',
    emoji: '🐕',
    body: 0xf4a460,
    bodyHighlight: 0xffdab9,
    ear: 0xd2691e,
    eyeColor: 0x222222,
    noseColor: 0x333333,
    earType: 'pointy',
    features: ['whiteCheeks', 'whiteBelly'],
  },
  husky: {
    id: 'husky',
    name: '허스키',
    emoji: '🐺',
    body: 0xa0aab4,
    bodyHighlight: 0xc0c8d0,
    ear: 0x808890,
    eyeColor: 0x4488cc,
    noseColor: 0x333333,
    earType: 'pointy',
    features: ['faceMask'],
  },
  samoyed: {
    id: 'samoyed',
    name: '사모예드',
    emoji: '🐻‍❄️',
    body: 0xfff8f0,
    bodyHighlight: 0xffffff,
    ear: 0xf0e8e0,
    eyeColor: 0x222222,
    noseColor: 0x333333,
    earType: 'round',
    features: ['fluffyFur'],
  },
  dachshund: {
    id: 'dachshund',
    name: '닥스훈트',
    emoji: '🌭',
    body: 0x8b4513,
    bodyHighlight: 0xa0522d,
    ear: 0x6b3410,
    eyeColor: 0x222222,
    noseColor: 0x222222,
    earType: 'floppy',
    features: ['longNose'],
  },
  dalmatian: {
    id: 'dalmatian',
    name: '달마시안',
    emoji: '🐾',
    body: 0xffffff,
    bodyHighlight: 0xf8f8f8,
    ear: 0xe0e0e0,
    eyeColor: 0x222222,
    noseColor: 0x111111,
    earType: 'round',
    features: ['spots'],
  },
  cat: {
    id: 'cat',
    name: '고양이',
    emoji: '\uD83D\uDC31',
    body: 0xf0c878,
    bodyHighlight: 0xf5dda0,
    ear: 0xd4a850,
    eyeColor: 0x44aa44,
    noseColor: 0xdd8899,
    earType: 'pointy',
    features: ['whiskers'],
  },
  rabbit: {
    id: 'rabbit',
    name: '토끼',
    emoji: '\uD83D\uDC30',
    body: 0xfce4ec,
    bodyHighlight: 0xfff0f5,
    ear: 0xf8bbd0,
    eyeColor: 0xcc3355,
    noseColor: 0xdd8899,
    earType: 'tall',
    features: ['whiteBelly'],
  },
  hamster: {
    id: 'hamster',
    name: '햄스터',
    emoji: '\uD83D\uDC39',
    body: 0xf5c07a,
    bodyHighlight: 0xfad9a1,
    ear: 0xd4a050,
    eyeColor: 0x222222,
    noseColor: 0xdd8899,
    earType: 'tiny',
    features: ['whiskers', 'whiteCheeks', 'belly'],
  },
  fox: {
    id: 'fox',
    name: '여우',
    emoji: '\uD83E\uDD8A',
    body: 0xe8741a,
    bodyHighlight: 0xf0944a,
    ear: 0xc05a10,
    eyeColor: 0xddaa22,
    noseColor: 0x222222,
    earType: 'pointy',
    features: ['whiteCheeks', 'tailBushy'],
  },
  raccoon: {
    id: 'raccoon',
    name: '너구리',
    emoji: '\uD83E\uDD9D',
    body: 0x9e9e9e,
    bodyHighlight: 0xbdbdbd,
    ear: 0x757575,
    eyeColor: 0x222222,
    noseColor: 0x333333,
    earType: 'round',
    features: ['blackEyeMask', 'stripes'],
  },
  penguin: {
    id: 'penguin',
    name: '펭귄',
    emoji: '\uD83D\uDC27',
    body: 0x2c3e50,
    bodyHighlight: 0x34495e,
    ear: 0x2c3e50,
    eyeColor: 0x222222,
    noseColor: 0xf39c12,
    earType: 'none',
    features: ['belly', 'beak'],
  },
};

const CHARACTER_IDS = Object.keys(CHARACTERS);
const DEFAULT_CHARACTER = 'poodle';

function isValidCharacter(id) {
  return CHARACTER_IDS.includes(id);
}

module.exports = { CHARACTERS, CHARACTER_IDS, DEFAULT_CHARACTER, isValidCharacter };
